[build]
  base = "web"
  command = "yarn install && yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.7"
  NPM_VERSION = "10.8.2"
  YARN_VERSION = "1.22.19"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096" 