[build]
  command = "cd web && npm install && npm run build"
  publish = "web/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4" 