[build]
  base = "web"
  command = "npm install && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_VERSION = "10.9.2"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--experimental-vm-modules" 