[build]
  command = "npm run build:web"
  publish = "web-build"

[context.production]
  [[plugins]]
    package = "@netlify/plugin-nextjs"
  [[plugins]]
    package = "expo-av"
  [[plugins]]
    package = "expo-device"
  [[plugins]]
    package = "expo-file-system"
  [[plugins]]
    package = "expo-sharing"
  [[plugins]]
    package = "expo-speech"
  [[plugins]]
    package = "expo-notifications"
  [[plugins]]
    package = "expo-updates"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 